name: libphonenumber
description: This is a Flutter implementation of libphonenumber. It includes only a few features at the moment, and are added when more functionality is desired.
version: 1.0.2
homepage: https://github.com/emostar/flutter-libphonenumber

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.2.3
  js: ^0.6.2

flutter:
  plugin:
    platforms:
      android:
        package: com.codeheadlabs.libphonenumber
        pluginClass: LibphonenumberPlugin
      ios:
        pluginClass: LibphonenumberPlugin
      web:
        pluginClass: LibphonenumberPlugin
        fileName: web/libphonenumber.dart        

environment:
  sdk: ">=1.19.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"
